// INGLY OS V2 — registro moduli, ESTRATTO da INGLY-OS-v96-STANDALONE.html
// (fonte di verità funzionale). NON inventato: generato dallo script di Fase 8.
// { s: sezione/route, n: nome, icon: emoji, group: categoria }
export const GROUP_ORDER = ["Home","AI","Preventivi","Vendite","Finanza","Clienti","Produzione","Magazzino","Analisi","Marketing","Sistema","Strumenti"];
export const MODULES = [
  {"s":"dashboard","n":"Dashboard ROI","icon":"📊","group":"Home"},
  {"s":"ai","n":"AI Decisioni","icon":"🤖","group":"AI"},
  {"s":"aicoach","n":"AI Coach","icon":"🧠","group":"AI"},
  {"s":"bizai","n":"Business AI Hub","icon":"🚀","group":"AI"},
  {"s":"forecasting","n":"AI Previsioni","icon":"🔮","group":"AI"},
  {"s":"decision","n":"Decision Engine","icon":"🎯","group":"AI"},
  {"s":"intel","n":"Intelligence Hub","icon":"⚡","group":"AI"},
  {"s":"market_agent","n":"Market AI Agent","icon":"🤖","group":"AI"},
  {"s":"studio_ai","n":"AI Studio","icon":"✨","group":"AI"},
  {"s":"quotes","n":"Preventivi","icon":"🧾","group":"Preventivi"},
  {"s":"quoter","n":"Smart Quoter","icon":"📄","group":"Preventivi"},
  {"s":"lasercalc","n":"🧮 Calc Laser","icon":"⚡","group":"Preventivi"},
  {"s":"print3d","n":"Smart Quote 3D","icon":"🖨️","group":"Preventivi"},
  {"s":"apparel","n":"Smart Quote Apparel","icon":"👕","group":"Preventivi"},
  {"s":"listino","n":"Listino B2B","icon":"💼","group":"Preventivi"},
  {"s":"template_docs","n":"Template Documenti","icon":"🎨","group":"Preventivi"},
  {"s":"quoteintel","n":"Quote Intelligence","icon":"📈","group":"Preventivi"},
  {"s":"invoices","n":"Fatture","icon":"🧮","group":"Vendite"},
  {"s":"aging","n":"Scadenziario","icon":"⏰","group":"Vendite"},
  {"s":"sales","n":"Vendite & Fatture","icon":"💰","group":"Vendite"},
  {"s":"sales_archive","n":"Archivio Vendite","icon":"📋","group":"Vendite"},
  {"s":"fiscal","n":"Radar Fiscale","icon":"📊","group":"Finanza"},
  {"s":"xmlsdi","n":"Fattura XML SDI","icon":"🧾","group":"Finanza"},
  {"s":"recurring","n":"Fatture Ricorrenti","icon":"🔄","group":"Finanza"},
  {"s":"taxcalendar","n":"Calendario Fiscale","icon":"📅","group":"Finanza"},
  {"s":"clients","n":"CRM Clienti","icon":"👥","group":"Clienti"},
  {"s":"clientintel","n":"Client Intelligence","icon":"🧠","group":"Clienti"},
  {"s":"clv","n":"CLV Clienti","icon":"👑","group":"Clienti"},
  {"s":"leadscorer","n":"Lead Scorer","icon":"⭐","group":"Clienti"},
  {"s":"b2bpitch","n":"B2B Pitch Builder","icon":"🤝","group":"Clienti"},
  {"s":"gestione_ordini","n":"Ordini & Workflow","icon":"📦","group":"Produzione"},
  {"s":"workflow_dashboard","n":"Workflow Overview","icon":"⚡","group":"Produzione"},
  {"s":"timetracker","n":"Time Tracker","icon":"⏱️","group":"Produzione"},
  {"s":"booking","n":"Booking","icon":"📅","group":"Produzione"},
  {"s":"scanner","n":"Scanner Spese","icon":"📷","group":"Produzione"},
  {"s":"items","n":"Magazzino","icon":"🗄️","group":"Magazzino"},
  {"s":"catalog","n":"Catalogo","icon":"📚","group":"Magazzino"},
  {"s":"gadgets","n":"Gadget & Accessori","icon":"🧩","group":"Magazzino"},
  {"s":"materials","n":"Materiali","icon":"🪵","group":"Magazzino"},
  {"s":"equipment","n":"Attrezzature","icon":"🔧","group":"Magazzino"},
  {"s":"paints","n":"Vernici & Bombolette","icon":"🎨","group":"Magazzino"},
  {"s":"components","n":"Componenti & Accessori","icon":"⚙️","group":"Magazzino"},
  {"s":"inventory","n":"Inventario","icon":"📋","group":"Magazzino"},
  {"s":"suppliers","n":"Fornitori","icon":"🚚","group":"Magazzino"},
  {"s":"purchases","n":"Acquisti","icon":"🛒","group":"Magazzino"},
  {"s":"barcode","n":"Barcode Scanner","icon":"📊","group":"Magazzino"},
  {"s":"finance","n":"Finance Pro","icon":"📊","group":"Finanza"},
  {"s":"cashflow","n":"Cashflow","icon":"💧","group":"Finanza"},
  {"s":"fixed_costs","n":"Costi Fissi","icon":"🧾","group":"Finanza"},
  {"s":"bank_funds","n":"Bank & Funds","icon":"🏦","group":"Finanza"},
  {"s":"profitscope","n":"ProfitScope","icon":"💰","group":"Finanza"},
  {"s":"dynamicprice","n":"Prezzi Dinamici","icon":"🔥","group":"Finanza"},
  {"s":"revsim","n":"Revenue Simulator","icon":"📈","group":"Finanza"},
  {"s":"goals","n":"Obiettivi","icon":"🎯","group":"Finanza"},
  {"s":"analytics","n":"Analytics","icon":"📊","group":"Analisi"},
  {"s":"kpi","n":"KPI Live","icon":"⚡","group":"Analisi"},
  {"s":"forecaster","n":"Financial Forecaster","icon":"📈","group":"Analisi"},
  {"s":"marketing","n":"Marketing Pro","icon":"📣","group":"Marketing"},
  {"s":"social","n":"Social Media","icon":"📱","group":"Marketing"},
  {"s":"socialstudio","n":"Social Studio","icon":"🎬","group":"Marketing"},
  {"s":"etsy","n":"Etsy Suite","icon":"🛍️","group":"Marketing"},
  {"s":"etsy_pulse","n":"Etsy Pulse Live","icon":"🔥","group":"Marketing"},
  {"s":"etsy_seo_wizard","n":"Etsy SEO Wizard","icon":"✨","group":"Marketing"},
  {"s":"trendscanner","n":"Trend Hunter","icon":"🔍","group":"Marketing"},
  {"s":"demand_map","n":"Demand Map","icon":"🗺️","group":"Marketing"},
  {"s":"product_hunter","n":"Product Hunter AI","icon":"🎯","group":"Marketing"},
  {"s":"live_intel","n":"Live Intel Feed","icon":"📡","group":"Marketing"},
  {"s":"price_radar","n":"Price Radar","icon":"📡","group":"Marketing"},
  {"s":"etsyai","n":"Etsy AI Suite","icon":"🤖","group":"Marketing"},
  {"s":"photostudio","n":"Photo Studio AI","icon":"📸","group":"Marketing"},
  {"s":"imagelib","n":"Libreria Immagini","icon":"🖼️","group":"Marketing"},
  {"s":"contentperf","n":"Content Performance","icon":"📊","group":"Marketing"},
  {"s":"replyai","n":"Reply Assistant","icon":"💬","group":"Marketing"},
  {"s":"socialproof","n":"Social Proof AI","icon":"⭐","group":"Marketing"},
  {"s":"marketintel","n":"Market Intel","icon":"🌐","group":"Marketing"},
  {"s":"competitors","n":"Competitor Monitor","icon":"🔍","group":"Marketing"},
  {"s":"settings","n":"Impostazioni","icon":"⚙️","group":"Sistema"},
  {"s":"backup","n":"Backup Locale","icon":"💾","group":"Sistema"},
  {"s":"portabile","n":"Esporta Portatile","icon":"☁️","group":"Sistema"},
  {"s":"history","n":"Storico","icon":"📋","group":"Sistema"},
  {"s":"reports","n":"Report PDF","icon":"📄","group":"Sistema"},
  {"s":"laserresources","n":"Risorse Laser","icon":"🔧","group":"Strumenti"},
  {"s":"lab_setup","n":"Lab & Lista Acquisti","icon":"🧪","group":"Strumenti"},
  {"s":"laser_b2b","n":"Laser B2B","icon":"💼","group":"Strumenti"},
  {"s":"opportunity","n":"Opportunity Scanner","icon":"🔭","group":"Analisi"},
  {"s":"growthengine","n":"Growth Engine","icon":"🚀","group":"Analisi"},
  {"s":"profitleak","n":"Profit Leak Detector","icon":"🔍","group":"Finanza"},
  {"s":"calendar","n":"Calendario","icon":"📅","group":"Strumenti"},
  {"s":"ideas","n":"Idee & Ispirazione","icon":"💡","group":"Strumenti"},
  {"s":"innovation","n":"Innovazione","icon":"🔬","group":"Strumenti"},
  {"s":"projects","n":"Progetti","icon":"📁","group":"Strumenti"},
  {"s":"strategy","n":"Strategia","icon":"♟️","group":"Strumenti"},
  {"s":"team","n":"Team & HR","icon":"👥","group":"Sistema"},
  {"s":"brand_identity","n":"Brand Identity","icon":"🎨","group":"Sistema"},
  {"s":"inglydesign","n":"Ingly Design","icon":"✏️","group":"Sistema"},
  {"s":"legal","n":"Legale","icon":"⚖️","group":"Sistema"},
  {"s":"fiera","n":"Fiera Assistant","icon":"🎪","group":"Strumenti"},
  {"s":"smartnotif","n":"Notifiche Smart","icon":"🔔","group":"Sistema"},
  {"s":"supplierintel","n":"Supplier Intelligence","icon":"🚚","group":"Magazzino"}
];
export function modulesByGroup() {
  const map = {};
  for (const g of GROUP_ORDER) map[g] = [];
  for (const m of MODULES) (map[m.group] ||= []).push(m);
  return map;
}
export function findModule(s) { return MODULES.find((m) => m.s === s) || null; }
